<%@ page contentType="text/html;charset=UTF-8" %>
<%
    String userName = (String) session.getAttribute("userName");
    if (userName == null) { response.sendRedirect("login.jsp"); return; }
%>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Dashboard • TN TechSympo 2026</title><link rel="stylesheet" href="css/style.css"></head>
<body class="page-bg"><header class="topbar"><div class="brand"><div class="brand-icon">TN</div><div class="brand-text-group"><span class="brand-main">VAR <span>CET</span></span><span class="brand-sub">Virudhunagar • Event Portal</span></div></div><nav><a href="dashboard.jsp" class="active">Dashboard</a><a href="events">Events</a><a href="myRegistrations">My Registrations</a><a href="logout" class="nav-btn">Logout</a></nav></header>
<main class="dashboard-shell"><section class="dashboard-banner"><div><div class="college-crest-badge"><span class="crest-dot"></span> PARTICIPANT PORTAL</div><h1>Hello, <span><%= userName %></span></h1><p>Explore the symposium, register for events and manage your participation.</p><div class="hero-actions"><a href="events" class="btn primary">Explore Events</a><a href="myRegistrations" class="btn outline">My Registrations</a></div></div><div class="dashboard-mark"><span>TN</span><strong>26</strong><small>TECHSYMP</small></div></section>
<section class="dashboard-grid"><a href="events" class="dash-card"><span>01</span><h2>Explore Events</h2><p>View events, schedules, venues, fees and seats.</p></a><a href="myRegistrations" class="dash-card"><span>02</span><h2>My Registrations</h2><p>View your TN26 registration codes and event details.</p></a><a href="logout" class="dash-card"><span>03</span><h2>Logout</h2><p>End your participant session securely.</p></a></section>
<section class="profile-panel"><div><p class="eyebrow">PROFILE</p><h2><%= userName %></h2></div><div class="profile-details"><div><span>Email</span><b><%= session.getAttribute("userEmail") %></b></div><div><span>Phone</span><b><%= session.getAttribute("userPhone") %></b></div><div><span>College</span><b><%= session.getAttribute("userCollege") %></b></div><div><span>Department</span><b><%= session.getAttribute("userDepartment") %></b></div><div><span>Year</span><b><%= session.getAttribute("userYear") %></b></div></div></section></main><footer class="footer">TN TechSympo 2026 • Participant Dashboard</footer></body></html>
