<%@ page contentType="text/html;charset=UTF-8" %>
<%@ page import="java.util.List" %>
<%@ page import="com.tnsymposium.Event" %>
<%
    List<Event> events = (List<Event>) request.getAttribute("events");
    if (events == null) { response.sendRedirect("events"); return; }
%>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Events • TN TechSympo 2026</title><link rel="stylesheet" href="css/style.css"></head>
<body class="page-bg"><header class="topbar"><div class="brand"><div class="brand-icon">TN</div><div class="brand-text-group"><span class="brand-main">VAR <span>CET</span></span><span class="brand-sub">Virudhunagar • Event Portal</span></div></div><nav><a href="index.jsp">Home</a><a href="events" class="active">Events</a><a href="login.jsp" class="nav-btn">Login</a></nav></header>
<main class="listing-shell"><section class="listing-head"><div><div class="college-crest-badge"><span class="crest-dot"></span> TECHNICAL • SYMPOSIUM EVENT DIRECTORY</div><h1>Choose your event.</h1><p>Live event information is loaded from the MySQL <strong>events</strong> table.</p></div><div class="event-count"><span><%= events.size() %></span><small>Active Events</small></div></section>
<% String error = request.getParameter("error"); if ("duplicate".equals(error)) { %><div class="alert error">You are already registered for this event.</div><% } else if ("full".equals(error)) { %><div class="alert error">This event is currently full.</div><% } else if ("server".equals(error)) { %><div class="alert error">Registration could not be completed due to a database exception.</div><% } %>
<div class="event-grid"><% if (events != null) { for (Event event : events) { %><article class="event-card"><div class="event-top"><span class="badge"><%= event.getCategory() %></span><span class="fee"><%= event.getFee() == 0 ? "FREE" : ("₹" + String.format("%.0f", event.getFee())) %></span></div><h2><%= event.getEventName() %></h2><p class="muted"><%= event.getDescription() %></p><div class="event-info"><span>📅 <b><%= event.getEventDate() %></b></span><span>⏰ <b><%= event.getStartTime() %></b></span><span>📍 <b><%= event.getVenue() %>, <%= event.getCity() %></b></span><span>👥 <b><%= event.getAvailableSeats() %> seats left</b></span></div><% if (event.getAvailableSeats() > 0) { %><a href="register-event?id=<%= event.getId() %>" class="btn primary event-btn">Register for this event →</a><% } else { %><button class="btn outline event-btn" disabled>Sold Out</button><% } %></article><% }} %></div></main><footer class="footer">VAR College of Engineering and Technology, Virudhunagar • Online Event Registration System</footer></body></html>
